# git-pack-refs
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-pack-refs.1
# using Deroffing man parser
complete -c git-pack-refs -l all --description 'The command by default packs all tags and refs … [See Man Page]'
complete -c git-pack-refs -l no-prune --description 'The command usually removes loose refs under $G… [See Man Page]'

