# git-update-server-info
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-update-server-info.1
# using Deroffing man parser
complete -c git-update-server-info -s f -l force --description 'Update the info files from scratch.'

