# git-peek-remote
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-peek-remote.1
# using Deroffing man parser
complete -c git-peek-remote -l upload-pack --description 'Use this to specify the path to git-upload-pack… [See Man Page]'

