# git-upload-pack
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-upload-pack.1
# using Deroffing man parser
complete -c git-upload-pack -l strict --description 'Do not try <directory>/.'
complete -c git-upload-pack -l timeout --description 'Interrupt transfer after <n> seconds of inactivity.'

