# git-var
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-var.1
# using Deroffing man parser
complete -c git-var -s l --description 'Cause the logical variables to be listed.'

