# git-prune-packed
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-prune-packed.1
# using Deroffing man parser
complete -c git-prune-packed -s n -l dry-run --description 'Don\\(cqt actually remove any objects, only show… [See Man Page]'
complete -c git-prune-packed -s q -l quiet --description 'Squelch the progress indicator.'

