# git-request-pull
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-request-pull.1
# using Deroffing man parser
complete -c git-request-pull -s p --description 'Show patch text.'

