# git-prune
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-prune.1
# using Deroffing man parser
complete -c git-prune -s n -l dry-run --description 'Do not remove anything; just report what it would remove.'
complete -c git-prune -s v -l verbose --description 'Report all removed objects.'
complete -c git-prune -l expire --description 'Only expire loose objects older than <time>.'

