# git-reset
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-reset.1
# using Deroffing man parser
complete -c git-reset -s q -l quiet --description 'Be quiet, only report errors.'
complete -c git-reset -l patch --description 'mode.  git reset [<mode>] [<commit>].'
complete -c git-reset -l soft --description '.'
complete -c git-reset -l mixed --description '.'
complete -c git-reset -l hard --description '.'
complete -c git-reset -l merge --description '.'
complete -c git-reset -l keep --description '.'
complete -c git-reset -l -------------------------------------------------- --description ' A       B     C    D     --soft   A       B   … [See Man Page]'

