# git-replace
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-replace.1
# using Deroffing man parser
complete -c git-replace -s f -l force --description 'If an existing replace ref for the same object … [See Man Page]'
complete -c git-replace -s d -l delete --description 'Delete existing replace refs for the given objects.'
complete -c git-replace -s l -l list --description 'List replace refs for objects that match the gi… [See Man Page]'

