# git-merge-index
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-merge-index.1
# using Deroffing man parser
complete -c git-merge-index -s a --description 'Run merge against all files in the index that need merging.'
complete -c git-merge-index -s o --description 'Instead of stopping at the first failed merge, … [See Man Page]'
complete -c git-merge-index -s q --description 'Do not complain about a failed merge program (a… [See Man Page]'

