# git-stripspace
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-stripspace.1
# using Deroffing man parser
complete -c git-stripspace -s s -l strip-comments --description 'Skip and remove all lines starting with comment… [See Man Page]'
complete -c git-stripspace -s c -l comment-lines --description 'Prepend comment character and blank to each line.'

