# git-tar-tree
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-tar-tree.1
# using Deroffing man parser
complete -c git-tar-tree -l remote --description 'Instead of making a tar archive from local repo… [See Man Page]'

