# git-check-mailmap
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-check-mailmap.1
# using Deroffing man parser
complete -c git-check-mailmap -l stdin --description 'Read contacts, one per line, from the standard … [See Man Page]'

