# git-difftool
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-difftool.1
# using Deroffing man parser
complete -c git-difftool -s d -l dir-diff --description 'Copy the modified files to a temporary location… [See Man Page]'
complete -c git-difftool -s y -l no-prompt --description 'Do not prompt before launching a diff tool.'
complete -c git-difftool -l prompt --description 'Prompt before each invocation of the diff tool.'
complete -c git-difftool -s t -l tool --description 'Use the diff tool specified by <tool>.'
complete -c git-difftool -l tool-help --description 'Print a list of diff tools that may be used with --tool.'
complete -c git-difftool -l '[no-]symlinks' --description 'git difftool\\(aqs default behavior is create sy… [See Man Page]'
complete -c git-difftool -s x -l extcmd --description 'Specify a custom command for viewing diffs.'
complete -c git-difftool -s g -l gui --description 'When git-difftool is invoked with the -g or --g… [See Man Page]'
complete -c git-difftool -l 'tool.' --description '.'
complete -c git-difftool -l no-symlinks --description 'instructs git difftool to create copies instead.'

