# git-mktree
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-mktree.1
# using Deroffing man parser
complete -c git-mktree -s z --description 'Read the NUL-terminated ls-tree -z output instead.'
complete -c git-mktree -l missing --description 'Allow missing objects.'
complete -c git-mktree -l batch --description 'Allow building of more than one tree object before exiting.'

