# git-commit-tree
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-commit-tree.1
# using Deroffing man parser
complete -c git-commit-tree -s p --description 'Each -p indicates the id of a parent commit object.'
complete -c git-commit-tree -s m --description 'A paragraph in the commit log message.'
complete -c git-commit-tree -s F --description 'Read the commit log message from the given file.'
complete -c git-commit-tree -o 'S[<keyid>]' --description 'GPG-sign commit.'

