# git-unpack-objects
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-unpack-objects.1
# using Deroffing man parser
complete -c git-unpack-objects -s n --description 'Dry run.'
complete -c git-unpack-objects -s q --description 'The command usually shows percentage progress.'
complete -c git-unpack-objects -s r --description 'When unpacking a corrupt packfile, the command … [See Man Page]'
complete -c git-unpack-objects -l strict --description 'Don\\(cqt write objects with broken content or links.'

