# gitweb
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/gitweb.1
# using Deroffing man parser
complete -c gitweb -l export-all --description 'option is used) allows pulling only for those r… [See Man Page]'

