# leaks
# Autogenerated from man page /usr/share/man/man1/leaks.1
# using Darwin man parser
complete -c leaks -o nocontext --description 'Do not print the string or hex representation of leaked memory.'
complete -c leaks -o nostacks --description 'Do not print backtraces of leaked blocks even i… [See Man Page]'
complete -c leaks -o exclude --description 'Exclude leaked blocks whose backtraces include … [See Man Page]'
complete -c leaks -o trace --description 'Print chains of references from process \'roots\' (e. g.'

