# npm-install
# Autogenerated from man page /usr/local/share/man/man1/npm-install.1
# using Deroffing man parser
complete -c npm-install -l save: --description '.'
complete -c npm-install -l save-dev: --description '.'
complete -c npm-install -l save-optional: --description '.'
complete -c npm-install -l save-exact: --description 'exact version rather than using npm\'s default s… [See Man Page]'

