# pandoc-citeproc
# Autogenerated from man page /usr/local/share/man/man1/pandoc-citeproc.1
# using Deroffing man parser
complete -c pandoc-citeproc -l 'help\\f[]' --description 'Print usage information. RS . RE.'
complete -c pandoc-citeproc -l 'version\\f[]' --description 'Print version. RS . RE.'
complete -c pandoc-citeproc -l 'bib2yaml\\f[]' --description 'Convert bibliography to YAML suitable for inclu… [See Man Page]'
complete -c pandoc-citeproc -l 'bib2json\\f[]' --description 'Convert bibliography to CSL JSON suitable for i… [See Man Page]'
complete -c pandoc-citeproc -l ---------- -l ------------ --description 'MODS              . mods BibLaTeX          .'
complete -c pandoc-citeproc -s h -l help --description 'Print usage information.'
complete -c pandoc-citeproc -s V -l version --description 'Print version.'
complete -c pandoc-citeproc -s y -l bib2yaml --description 'Convert bibliography to YAML suitable for inclu… [See Man Page]'
complete -c pandoc-citeproc -s j -l bib2json --description 'Convert bibliography to CSL JSON suitable for i… [See Man Page]'
complete -c pandoc-citeproc -s f -l format --description 'Specify format of bibliography to be converted.'

