# symbols
# Autogenerated from man page /usr/share/man/man1/symbols.1.gz
# using Darwin man parser
complete -c symbols -o help --description 'Print a more extensive list of options.'
complete -c symbols -s v --description 'Print version information.'
complete -c symbols -s w --description 'Print wide output, do not clip to terminal width.'
complete -c symbols -o uuid --description 'Print UUID info only.'
complete -c symbols -o arch --description 'Specify the target architecture.'
complete -c symbols -o cpuTpe --description 'Specify the target architecture cpu type as a numeric value.'
complete -c symbols -o cpuSubtype --description 'Specify the target architecture cpu subtype as a numeric value.'
complete -c symbols -o noHeaders --description 'Do not print library level information.'
complete -c symbols -o noRegions --description 'Do not print segment/section level information.'
complete -c symbols -o noSymbols --description 'Do not print symbol level information.'
complete -c symbols -o noSources --description 'Do not print source level information.'
complete -c symbols -o noDemangling --description 'Do not print the human readable form of symbol … [See Man Page]'
complete -c symbols -o printSignature --description 'Print a "signature" for each target, which can … [See Man Page]'
complete -c symbols -o deepSignature --description 'Causes all signatures to be "deep copies", cont… [See Man Page]'
complete -c symbols -o fullSourcePath --description 'Print the entire source path for each source info.'
complete -c symbols -o printDsymPaths --description 'Print the path of the dSYM file (if found) used… [See Man Page]'
complete -c symbols -o lookup --description 'Find one or more addresses or symbols in the targets.'

