# Xephyr
# Autogenerated from man page /opt/X11/share/man/man1/Xephyr.1
# using Deroffing man parser
complete -c Xephyr -o screen --description 'sets the screen size.'
complete -c Xephyr -o parent --description 'uses exiting window  id .'
complete -c Xephyr -o host-cursor --description 'set \'cursor acceleration\': The host\'s cursor is reused.'

